version: "3.2"

services:
  kylin-collator-westend:
    container_name: kylin-collator-westend
    image: kylinnetwork/kylin-collator:main
    ports:
      - "9942:9942"
      - "9930:9930"
      - "30333:30333"
      - "30334:30334"
    command: bash -c "wget https://raw.githubusercontent.com/Kylin-Network/kylin-collator/main/res/pichiu-westend-spec.json;/kylin-collator --unsafe-ws-external --rpc-cors all  --rpc-external --rpc-methods Unsafe -d cumulus_parachain/kylin-collator-1 --collator --name pichiu-collator-1 --ws-port 9942 --port 30333 --rpc-port 9930 --parachain-id 2106 --chain pichiu-westend-spec.json --execution=Native --  --port 30334 --chain westend --execution=wasm  --sync fast --pruning archive"
    volumes:
      - ./kylin_db/cumulus_parachain:/cumulus_parachain/

  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"
    depends_on:
      - kylin-collator-westend
