version: "3.2"

services:
  launch:
    container_name: launch
    image: kylinnetwork/kylin-collator:main
    ports:
      - "30330-30345:30330-30345"
      - "9933-9960:9933-9960"
    command: bash -c "cd polkadot-launch; rm *.log;polkadot-launch kylinLaunchConfig.json"
    volumes:
      - ./polkadot-launch/:/polkadot-launch/

  frontend:
    container_name: frontend
    image: jacogr/polkadot-js-apps
    ports:
      - "3001:80"