version: "3.2"

services:
  kylin-data-proxy:
    container_name: kylin-data-proxy
    image: kylinnetwork/kylin-node:latest
    ports:
      - "8080:8080"
    environment:
      - KYLIN_ES_HOST=kylin-es:9200
    command: bash -c "/data_fetcher"
    depends_on:
      - init-es-index

  validator_1:
    container_name: validator_1
    image: kylinnetwork/kylin-node:latest
    ports:
      - "9934:9934"
      - "9944:9944"
      - "30333:30333"
    command: bash -c "/polkadot --unsafe-ws-external --rpc-cors all --rpc-external --rpc-methods Unsafe --chain rococo -d cumulus_relay/alice --validator --alice --ws-port 9944 --port 30333 --rpc-port 9934 --name alice"

  validator_2:
    container_name: validator_2
    image: kylinnetwork/kylin-node:latest
    ports:
      - "9935:9935"
      - "9955:9955"
      - "30334:30334"
    command: bash -c "/polkadot --unsafe-ws-external --rpc-cors all --rpc-external --rpc-methods Unsafe --chain rococo -d cumulus_relay/bob --validator --bob --ws-port 9955 --port 30334 --rpc-port 9935 --name bob"
    depends_on:
      - validator_1

  kylin-node:
    container_name: kylin-node
    image: kylinnetwork/kylin-node:latest
    ports:
      - "9942:9942"
      - "9933:9933"
    command: bash -c "/kylin-node --unsafe-ws-external --rpc-cors all --rpc-external --rpc-methods Unsafe -d cumulus-parachain/alice --collator --alice --ws-port 9942 --rpc-port 9933 --parachain-id 2005 -- --execution wasm --chain rococo"
    depends_on:
      - validator_2

  insert-ocw:
    container_name: insert-ocw
    image: kylinnetwork/kylin-node:latest
    command: bash -c "sleep 30 && /insert_alice_key.sh"
    depends_on:
      - kylin-node

  kylin-market-frontend:
    container_name: kylin-market-frontend
    image: kylinnetwork/kylin-node:latest
    ports:
      - "3001:3001"
    command: bash -c "cd /apps && serve -p 3001 build"
    depends_on:
      - kylin-node

  kylin-es:
    container_name: kylin-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kylin-kibana:
    container_name: kylin-kibana
    ports:
      - "5601:5601"
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      ELASTICSEARCH_HOSTS: http://kylin-es:9200
    depends_on:
      - kylin-es

  init-es-index:
    container_name: init-es-index
    image: kylinnetwork/kylin-node:latest
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 60 && /init_es_index.sh"
    depends_on:
      - kylin-es
      - kylin-kibana

  init-kibana-dashboard:
    container_name: init-kibana-dashboard
    image: kylinnetwork/kylin-node:latest
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 120 && /init_kibana_dashboard.sh"
    depends_on:
      - kylin-es
      - kylin-kibana
volumes:
  es-data:
    driver: local

